"""Initial schema with all models

Revision ID: 4141aabbf97d
Revises: 
Create Date: 2025-08-17 14:52:08.595831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4141aabbf97d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True, comment='User role (researcher, admin, etc.)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Email verification status'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('max_projects', sa.Integer(), nullable=True, comment='Maximum number of concurrent projects'),
    sa.Column('api_rate_limit', sa.Integer(), nullable=True, comment='API calls per hour limit'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active', 'users', ['is_active', 'is_verified'], unique=False)
    op.create_index('idx_user_login', 'users', ['last_login', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_keys',
    sa.Column('key_hash', sa.String(length=255), nullable=False, comment='SHA256 hash of the API key'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Descriptive name for the key'),
    sa.Column('description', sa.String(length=1000), nullable=True, comment='Detailed description of key purpose'),
    sa.Column('permissions', sa.JSON(), nullable=False, comment='List of permission strings'),
    sa.Column('rate_limit', sa.Integer(), nullable=True, comment='Requests per hour limit (null = use user default)'),
    sa.Column('allowed_ips', sa.JSON(), nullable=True, comment='List of allowed IP addresses/ranges'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Key expiration time (null = never expires)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='When the key was revoked'),
    sa.Column('revoked_reason', sa.String(length=500), nullable=True, comment='Reason for revocation'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_apikey_expires', 'api_keys', ['expires_at', 'is_active'], unique=False)
    op.create_index('idx_apikey_last_used', 'api_keys', ['last_used_at'], unique=False)
    op.create_index('idx_apikey_user_active', 'api_keys', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_deleted_at'), 'api_keys', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_api_keys_expires_at'), 'api_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_last_used_at'), 'api_keys', ['last_used_at'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('research_projects',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('domains', sa.JSON(), nullable=False, comment='List of research domains'),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True, comment='Overall quality score (0.0 to 1.0)'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=True, comment='Temporal or LangGraph workflow ID'),
    sa.Column('metadata', sa.JSON(), nullable=False, comment='Additional project metadata'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_quality', 'research_projects', ['quality_score', 'status'], unique=False)
    op.create_index('idx_project_user_status', 'research_projects', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_project_workflow', 'research_projects', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_research_projects_deleted_at'), 'research_projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_research_projects_status'), 'research_projects', ['status'], unique=False)
    op.create_index(op.f('ix_research_projects_title'), 'research_projects', ['title'], unique=False)
    op.create_index(op.f('ix_research_projects_user_id'), 'research_projects', ['user_id'], unique=False)
    op.create_index(op.f('ix_research_projects_workflow_id'), 'research_projects', ['workflow_id'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=False, comment='Type of agent (e.g., literature_review, synthesis)'),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', 'RETRYING', name='taskstatus'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False, comment='Input data for the agent'),
    sa.Column('output_data', sa.JSON(), nullable=True, comment='Output data from the agent'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if task failed'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of retry attempts'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True, comment='Execution time in milliseconds'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Task priority (higher = more important)'),
    sa.Column('depends_on', sa.JSON(), nullable=True, comment='List of task IDs this task depends on'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_agent_status', 'agent_tasks', ['agent_type', 'status'], unique=False)
    op.create_index('idx_task_priority', 'agent_tasks', ['priority', 'status'], unique=False)
    op.create_index('idx_task_project_status', 'agent_tasks', ['project_id', 'status'], unique=False)
    op.create_index('idx_task_started', 'agent_tasks', ['started_at', 'status'], unique=False)
    op.create_index(op.f('ix_agent_tasks_agent_type'), 'agent_tasks', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_tasks_deleted_at'), 'agent_tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_agent_tasks_project_id'), 'agent_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_started_at'), 'agent_tasks', ['started_at'], unique=False)
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.create_table('research_results',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('result_type', sa.String(length=50), nullable=False, comment='Type of result (finding, source, citation, etc.)'),
    sa.Column('content', sa.JSON(), nullable=False, comment='Result content (structure varies by type)'),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='Confidence score for the result (0.0 to 1.0)'),
    sa.Column('agent_type', sa.String(length=100), nullable=True, comment='Agent that produced this result'),
    sa.Column('metadata', sa.JSON(), nullable=False, comment='Additional metadata'),
    sa.Column('source_id', sa.String(length=500), nullable=True, comment='External source identifier (DOI, URL, etc.)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_result_agent', 'research_results', ['project_id', 'agent_type'], unique=False)
    op.create_index('idx_result_confidence', 'research_results', ['confidence_score', 'result_type'], unique=False)
    op.create_index('idx_result_project_type', 'research_results', ['project_id', 'result_type'], unique=False)
    op.create_index('idx_result_source', 'research_results', ['source_id'], unique=False)
    op.create_index(op.f('ix_research_results_agent_type'), 'research_results', ['agent_type'], unique=False)
    op.create_index(op.f('ix_research_results_deleted_at'), 'research_results', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_research_results_project_id'), 'research_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_research_results_result_type'), 'research_results', ['result_type'], unique=False)
    op.create_index(op.f('ix_research_results_source_id'), 'research_results', ['source_id'], unique=False)
    op.create_table('workflow_checkpoints',
    sa.Column('workflow_id', sa.String(length=255), nullable=False, comment='Temporal or LangGraph workflow ID'),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('checkpoint_data', sa.JSON(), nullable=False, comment='Serialized workflow state'),
    sa.Column('phase', sa.String(length=100), nullable=False, comment='Workflow phase at checkpoint'),
    sa.Column('checkpoint_type', sa.String(length=50), nullable=False, comment='Type of checkpoint (automatic, manual, error)'),
    sa.Column('checkpoint_version', sa.String(length=50), nullable=True, comment='Version of checkpoint format'),
    sa.Column('is_recoverable', sa.Boolean(), nullable=False, comment='Whether this checkpoint can be used for recovery'),
    sa.Column('recovery_metadata', sa.JSON(), nullable=True, comment='Additional data needed for recovery'),
    sa.Column('execution_metrics', sa.JSON(), nullable=True, comment='Performance metrics at checkpoint time'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_checkpoint_project_phase', 'workflow_checkpoints', ['project_id', 'phase'], unique=False)
    op.create_index('idx_checkpoint_recoverable', 'workflow_checkpoints', ['is_recoverable', 'workflow_id'], unique=False)
    op.create_index('idx_checkpoint_workflow', 'workflow_checkpoints', ['workflow_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_workflow_checkpoints_deleted_at'), 'workflow_checkpoints', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workflow_checkpoints_phase'), 'workflow_checkpoints', ['phase'], unique=False)
    op.create_index(op.f('ix_workflow_checkpoints_project_id'), 'workflow_checkpoints', ['project_id'], unique=False)
    op.create_index(op.f('ix_workflow_checkpoints_workflow_id'), 'workflow_checkpoints', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_checkpoints_workflow_id'), table_name='workflow_checkpoints')
    op.drop_index(op.f('ix_workflow_checkpoints_project_id'), table_name='workflow_checkpoints')
    op.drop_index(op.f('ix_workflow_checkpoints_phase'), table_name='workflow_checkpoints')
    op.drop_index(op.f('ix_workflow_checkpoints_deleted_at'), table_name='workflow_checkpoints')
    op.drop_index('idx_checkpoint_workflow', table_name='workflow_checkpoints')
    op.drop_index('idx_checkpoint_recoverable', table_name='workflow_checkpoints')
    op.drop_index('idx_checkpoint_project_phase', table_name='workflow_checkpoints')
    op.drop_table('workflow_checkpoints')
    op.drop_index(op.f('ix_research_results_source_id'), table_name='research_results')
    op.drop_index(op.f('ix_research_results_result_type'), table_name='research_results')
    op.drop_index(op.f('ix_research_results_project_id'), table_name='research_results')
    op.drop_index(op.f('ix_research_results_deleted_at'), table_name='research_results')
    op.drop_index(op.f('ix_research_results_agent_type'), table_name='research_results')
    op.drop_index('idx_result_source', table_name='research_results')
    op.drop_index('idx_result_project_type', table_name='research_results')
    op.drop_index('idx_result_confidence', table_name='research_results')
    op.drop_index('idx_result_agent', table_name='research_results')
    op.drop_table('research_results')
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_started_at'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_project_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_deleted_at'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_agent_type'), table_name='agent_tasks')
    op.drop_index('idx_task_started', table_name='agent_tasks')
    op.drop_index('idx_task_project_status', table_name='agent_tasks')
    op.drop_index('idx_task_priority', table_name='agent_tasks')
    op.drop_index('idx_task_agent_status', table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_research_projects_workflow_id'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_user_id'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_title'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_status'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_deleted_at'), table_name='research_projects')
    op.drop_index('idx_project_workflow', table_name='research_projects')
    op.drop_index('idx_project_user_status', table_name='research_projects')
    op.drop_index('idx_project_quality', table_name='research_projects')
    op.drop_table('research_projects')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_last_used_at'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_expires_at'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_deleted_at'), table_name='api_keys')
    op.drop_index('idx_apikey_user_active', table_name='api_keys')
    op.drop_index('idx_apikey_last_used', table_name='api_keys')
    op.drop_index('idx_apikey_expires', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index('idx_user_login', table_name='users')
    op.drop_index('idx_user_active', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
